### ISSUE TITLE
setting flutter_sdk path to local fvm flutter_sdk results in exception

### ISSUE THREAD

**Issue by knyghtryda** [alexei-sintotski/dart-borg#101]
I have set the flutter_sdk to this:
```yaml
include: # list of locations processed by Borg, glob specifications are allowed
  - .
exclude: # specify here a list of locations to be ignored by Borg
  - .fvm/
dart_sdk:  # path to Dart SDK
flutter_sdk: # path to the root of Flutter SDK
  - .fvm/flutter_sdk/
```
However I'm getting this exception when running `borg boot`: 
```shell
❯ borg boot
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'String' in type cast
#0      _getString (package:borg/src/configuration/configuration.dart:65:29)
#1      new BorgConfiguration.fromJson (package:borg/src/configuration/configuration.dart:55:25)
#2      _constructConfigFromFile.<anonymous closure> (package:borg/src/configuration/factory.dart:121:36)
#3      Optional.iif (package:plain_optional/src/optional.dart:13:95)
#4      _constructConfigFromFile (package:borg/src/configuration/factory.dart:120:68)
#5      new BorgConfigurationFactory (package:borg/src/configuration/factory.dart:49:26)
#6      new ProbeCommand (file:///Users/yanminhong/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/src/commands/probe_command.dart:64:7)
#7      main (file:///Users/yanminhong/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/main.dart:39:20)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
removing the flutter_sdk allows for probe, init, etc, but boot fails.
